### ISSUE TITLE
Z offset setting--offer to type in a value

### ISSUE THREAD

**Issue by lunatic1972** [johncarlson21/SV04-Marlin-2.1.x#2]
Having tried the "stock" firmware and now 2 versions into your amazing upgrade of the touch screen and marlin code base, would you be able to type in a value for the z-offset page(s)? I'm only asking because since it was changed from 0.05 step to 0.01 step it does take awhile to get to the correct offset. Mine just happened to be -1.36. It seems sometimes when the firmware is updated, it zeros the value and I've taken pictures of z-offset along with x/y offsets for nozzle. I think this would just add a little to an already great release. Thanks again for your time

**Comment by johncarlson21** [comment]
This is added to Screen Version 1.2.7 and Printer Version 2.1.3.1b3
Please Update your machine to enable it.
