### ISSUE TITLE
[Wrong extruder] Uses wrong extruder in single mode

### ISSUE THREAD

**Issue by rainey832** [johncarlson21/SV04-Marlin-2.1.x#4]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

 If you print something in single mode and then immediately print that same thing again without turning it off it decides to use the second extruder.

### Bug Timeline

New

### Expected behavior

Expected to use the selected extruder in single mode whenever which extruder is used isn't specified in starting gcode

### Actual behavior

Printer will use the selected extruder once, but if that print completes and you immediately start the same print with the same extruder selected again it will alternate to the opposite extruder. In this case it alternated to extruder 2. This is fixed by power cycling. Then you can select whichever extruder and it will use the expected extruder.

### Steps to Reproduce

1. Slice any STL and do not specify which extruder its to use in starting gcode.
2. Print file, and then immediately print it again with the same extruder selected in single mode.
3. Printer then will alternate to the secondary extruder.

### Version of Marlin Firmware

2.1.2

### Printer model

Sovol SV04

### Electronics

Stock

### Add-ons

Stock

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by johncarlson21** [comment]
Please upload your gcode file you are testing with so I can see it.. I just sliced using cura and removed the calls to the extruder to set it, and it seems to be working for me. I will post a video to your FB comment.

Also you should, never NOT set the extruder and let the printer guess.

**Comment by rainey832** [comment]
I've attached the gcode file. Thank you for time with this. So I was under the impression since I can choose which extruder to use in the mode selection touchscreen, I could take a single extruded gcode file and pick on the printer which extruder it uses. If i'm to always set the extruder to T0 for a single extruded file for example, would I still be able to select extruder 2 on the printer itself and have it use extruder 2?

**Comment by rainey832** [comment]
[LIGHTSABER-HILT_BLACK_12h50m_LH0.16mm_N0.6mm.Zip](https://github.com/johncarlson21/SV04-Marlin-2.1.x/files/10777256/LIGHTSABER-HILT_BLACK_12h50m_LH0.16mm_N0.6mm.Zip)

Sorry had to zip

**Comment by rainey832** [comment]
Sorry again, I sent a dual extrude file
[OBI-WAN-LIGHTSABER-CAP_1h1m_LH0.16mm_N0.6mm.zip](https://github.com/johncarlson21/SV04-Marlin-2.1.x/files/10777266/OBI-WAN-LIGHTSABER-CAP_1h1m_LH0.16mm_N0.6mm.zip)

**Comment by johncarlson21** [comment]
Yep your end code is setting T1.
Have a look at this pic.. Line 144437
<img width="445" alt="Screen Shot 2023-02-19 at 10 00 32 AM" src="https://user-images.githubusercontent.com/25893/219959618-db7fb117-c8ed-49c2-afd7-dcfd40833dff.png">

**Comment by johncarlson21** [comment]
Need to make sure you are using the correct slicing printer profile for this or check your printer end code..
but my suggestion is to let the slicer define the extruder.

**Comment by rainey832** [comment]
Wow that is fascinating thanks, I didn't realize that would carry to the next print. Alright so not a bug. Thanks again
