### ISSUE TITLE
Esteps 

### ISSUE THREAD

**Issue by Piccyman** [johncarlson21/SV04-Marlin-2.1.x#7]
**On the esteps adjustment, there should be x and y and z for each extruder.
Lovely add-on

**Comment by johncarlson21** [comment]
I looked into this for another machine I built and you cannot set the esteps independently for x or y

I've only put this in for the extruder motor

I believe you can set for the z but have not looked into this.

**Comment by johncarlson21** [comment]
I will be adding X, Y, Z steps to the next update of the screen and the firmware.

**Comment by Piccyman** [comment]
Thank you, I did ask a question on Facebook, is linear advance enabled ?

**Comment by johncarlson21** [comment]
Yes it is, and it does have some default set.
I'm not really familiar with linear advance etc.. I know if you want to get it just right you need to do some testing.

**Comment by johncarlson21** [comment]
This is now updated in the V2.1.3.1b3 pre-release. You also need to update your screen to 1.2.7
Linear Advance is enabled and I've change the K value to 0 so it is basically disabled. You can use a PC to update your values for K.
