### ISSUE TITLE
Z offset

### ISSUE THREAD

**Issue by Piccyman** [johncarlson21/SV04-Marlin-2.1.x#8]
The z offset indicates .001mm + or -, but the movement when pressed is 0.1mm, i measured it with feeler gauges.
![PXL_20230316_105235010](https://user-images.githubusercontent.com/114619464/225942667-67ce2608-5263-47e8-84a3-77caa6770e76.jpg)

**Comment by johncarlson21** [comment]
What version of the printer firmware are you on and what version of the screen firmware?

**Comment by johncarlson21** [comment]
You are correct, I found that the increment number was wrong.. I am adding this to the next fix.

**Comment by johncarlson21** [comment]
I've fixed this in 2.1.3.1b

**Comment by johncarlson21** [comment]
actually I think I need to fix something in the display also

**Comment by johncarlson21** [comment]
I've added a fix to the display also.

**Comment by johncarlson21** [comment]
This is now pushed so you can update your screen to V1.2.7 and also update your printer firmware, I would suggest updating it to the pre-release V2.1.3.1b3
